import React from 'react';
import CodeExample from '@/components/CodeExample';
import { C, H2, LI, Lead, P, Table, UL } from '../components/Prose';

export default function OpenApiContent() {
  return (
    <>
      <Lead>
        An OpenAPI document describes your API in a format tools understand: Swagger UI, Postman, client generators for a dozen languages. Luxid builds one from your code.
      </Lead>

      <H2>Getting one</H2>

      <CodeExample
        language="sh"
        code={`cargo luxid openapi > openapi.json
cargo luxid openapi --pretty --title "Blog API" --version 1.0.0`}
      />

      <P>Every registered route appears, whether or not you documented it.</P>

      <H2>Documenting an action</H2>

      <CodeExample
        language="rust"
        code={`#[luxid::controller]
impl PostsController {
    #[openapi(summary = "List posts", tag = "posts", ok = PageOfPosts)]
    async fn index(ctx: HttpContext) -> Result<Response> { /* ... */ }

    #[openapi(tag = "posts", ok = PostView, errors = [404])]
    async fn show(ctx: HttpContext) -> Result<Response> { /* ... */ }

    #[openapi(body = StorePost, created = PostView, errors = [422, 409])]
    async fn store(ctx: HttpContext) -> Result<Response> { /* ... */ }

    #[openapi(no_content, errors = [404])]
    async fn destroy(ctx: HttpContext) -> Result<Response> { /* ... */ }
}`}
      />

      <Table
        headers={['Key', 'Meaning']}
        rows={[
            [<span key={0}><C>summary = "..."</C></span>, <span key={1}>One-line description</span>],
            [<span key={0}><C>tag = "..."</C></span>, <span key={1}>Groups related endpoints</span>],
            [<span key={0}><C>body = T</C></span>, <span key={1}>Request body schema</span>],
            [<span key={0}><C>ok = T</C></span>, <span key={1}>200 with this schema</span>],
            [<span key={0}><C>created = T</C></span>, <span key={1}>201</span>],
            [<span key={0}><C>accepted = T</C></span>, <span key={1}>202</span>],
            [<span key={0}><C>no_content</C></span>, <span key={1}>204, no body</span>],
            [<span key={0}><C>errors = [422, 404]</C></span>, <span key={1}>Which failures this endpoint produces</span>],
        ]}
      />

      <H2>Types need <C>JsonSchema</C></H2>

      <P>Any type named in <C>body</C>, <C>ok</C>, <C>created</C> or <C>accepted</C> must derive it:</P>

      <CodeExample
        language="rust"
        code={`use luxid::JsonSchema;
use serde::Serialize;

#[derive(Serialize, JsonSchema)]
pub struct PostView {
    pub id: i64,
    pub title: String,
}`}
      />

      <P>Generated form requests already derive it. Note that a generated app declares <C>schemars</C> directly in its <C>Cargo.toml</C> — the derive emits <C>schemars::</C> paths, so re-exporting it through <C>luxid</C> is not enough for <C>#[derive(..)]</C> to resolve. <C>luxid new</C> sets this up for you.</P>

      <H2>What you get for free</H2>

      <P><strong>Error schemas.</strong> You write <C>errors = [422]</C>; the document gets a <C>application/problem+json</C> response referencing a shared <C>Problem</C> component, with the field-error map described. You never write that shape.</P>

      <P><strong>Path parameters.</strong> <C>/posts/{'{'}id{'}'}</C> produces the <C>id</C> parameter automatically, derived from the route pattern — so it can never disagree with the route.</P>

      <P><strong>Operation ids.</strong> Each operation is identified as <C>PostsController::show</C>, which client generators turn into method names.</P>

      <H2>Undocumented actions still appear</H2>

      <P>An action with no attribute is present but bare:</P>

      <CodeExample
        language="json"
        code={`"/api/health": {
  "get": {
    "operationId": "HealthController::show",
    "responses": { "default": { "description": "Undocumented" } }
  }
}`}
      />

      <P>Omitting it would make the document quietly lie about what your API exposes. A marked-undocumented endpoint is honest; a missing one is not.</P>

      <H2>OpenAPI 3.1</H2>

      <P>Luxid emits 3.1 rather than 3.0 because <strong>3.1 <em>is</em> JSON Schema</strong>. Schemas generated by <C>schemars</C> drop in unchanged rather than being translated into 3.0's near-miss dialect.</P>

      <P>Most modern tooling handles 3.1. If yours does not, a converter is easier than degrading the schemas.</P>

      <H2>Serving the document</H2>

      <CodeExample
        language="rust"
        code={`pub struct DocsController;

#[luxid::controller]
impl DocsController {
    async fn openapi(ctx: HttpContext) -> Result<Response> {
        // Embedded at build time by \`cargo luxid openapi > openapi.json\`.
        ctx.response
            .header("content-type", "application/json")
            .text(include_str!("../../openapi.json"))
    }
}`}
      />

      <P>Generating it in CI and committing the result also gives you a reviewable diff when your API surface changes — which is often exactly the review you want.</P>

      <H2>Keeping it honest</H2>

      <P>The attribute restates types the body already mentions, so it can drift. Two habits help:</P>

      <UL>
        <LI key={0}><strong>Regenerate in CI</strong> and fail if <C>openapi.json</C> changed without being committed. A drifted document is worse than none.</LI>
        <LI key={1}><strong>Document errors as you add them.</strong> When you add a <C>Conflict</C> to an action, add <C>409</C> to its <C>errors</C> list in the same commit.</LI>
      </UL>

      <H2>Why the route table, not a registry</H2>

      <P>Some frameworks collect documentation into a global registry at startup, using linker tricks. Luxid walks the <strong>route table</strong> instead — the same explicit registration a request goes through.</P>

      <P>The practical consequence: a route missing from your document is a route missing from <C>cargo luxid routes</C>. There is no third place where an endpoint might be hiding.</P>

    </>
  );
}
